version: '3.8'
services:
  app:
    container_name: napoleonic-client
    image: joebri/napoleonic-client
    restart: always
    build:
      # Path to dockerfile
      context: ./
      target: production
    ports:
      - '3001:3000'
